overwrite: true
schema: './src/graphql/modules/**/*.graphql'
generates:
  ./src/generated/:
    preset: '@eddeee888/gcg-typescript-resolver-files'
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      useIndexSignature: true
    presetConfig:
      resolverTypesPath: ./types.generated.ts
      typesPluginsConfig:
        contextType: "../context#MyContext"
        optionalResolveType: false,
        skipTypename: true,
  
  ./src/generated/knex-types.ts:
    plugins:
      - ./src/codegen/knex-types-plugin.js

hooks:
  afterOneFileWrite: ['prettier --write "src/generated/**/*.ts"']
